# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Execute pre-deployment tests
      run: mvn test
    - name: Package jar file
      run: mvn package -DskipTests
    - name: Deploy on Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with: 
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "pragmatest-workshop"
        heroku_email: "dre086@gmail.com"


